import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faJs,
  faWordpress,
  faPhp,
  faHtml5,
  faCss3,
  faNodeJs,
  faReact,
  faSass,
  faCloudflare,
} from "@fortawesome/free-brands-svg-icons";
import { faDatabase } from "@fortawesome/free-solid-svg-icons";
import {
  SiMongodb,
  SiNestjs,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

export const allPortfolioData = [
  {
    title: "Seagrid App",
    description: "React native app",
    imageUrl: "/seagrid-app.png",
    link: "https://play.google.com/store/apps/details?id=se.seagrid",
    category: "Work",
    techUsed: [
      <FontAwesomeIcon icon={faReact} />,
      <SiTypescript />,
      <SiTailwindcss />,
      <SiMongodb />,
      <SiNestjs />,
    ],
  },
  {
    title: "Planeringsverktyget",
    description: "Wordpress plugin",
    imageUrl: "/planeringsverktyget.png",
    link: "https://github.com/gutamuw/my-react-plugin",
    category: "Work",
    techUsed: [
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faPhp} />,
      <FontAwesomeIcon icon={faReact} />,
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "Begravningar.se",
    description: "Map search feature",
    imageUrl: "/begravningarse.png",
    link: "https://www.begravningar.se/",
    category: "Freelance",
    techUsed: [
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faPhp} />,
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "Elagent.com",
    description: "Website project & SEO",
    imageUrl: "/elagent-screenshot.png",
    link: "https://elagent.com/",
    category: "Freelance",
    techUsed: [
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "Seagrid single sign-on",
    description: "Firebase authentication plugin",
    imageUrl: "/seagrid_sso.jpg",
    link: "https://www.seagrid.se/app-login/  ",
    category: "Internship",
    techUsed: [
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faPhp} />,
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
      <FontAwesomeIcon icon={faCloudflare} />,
    ],
  },
  {
    title: "Livsarkivet.se",
    description: "Website project",
    imageUrl: "/livsarkivet.png",
    link: "https://www.livsarkivet.se/",
    category: "Work",
    techUsed: [
      <FontAwesomeIcon icon={faPhp} />,
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "Älvkarleby",
    description: "Website project",
    imageUrl: "/alvkarleby-screenshot.png",
    link: "https://www.alvkarlebybegravningsbyra.se/",
    category: "Work",
    techUsed: [
      <FontAwesomeIcon icon={faPhp} />,
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "Sandstedts.se",
    description: "Website project",
    imageUrl: "/sandstedts-screenshot.png",
    link: "https://www.sandstedt.se/",
    category: "Work",
    techUsed: [
      <FontAwesomeIcon icon={faPhp} />,
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "Rogerelverskog.se",
    description: "Website project",
    imageUrl: "/roger-screenshot.png",
    link: "https://rogerelverskog.se/",
    category: "Freelance",
    techUsed: [
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "Superbgroup.se",
    description: "Website project",
    imageUrl: "/superb_screenshot.png",
    link: "https://superbgroup.se/",
    category: "Freelance",
    techUsed: [
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
  {
    title: "TheChat",
    description: "API & WebSocket",
    imageUrl: "/theChat-screenshot.JPG",
    link: "https://github.com/gutamuw/theChat",
    category: "Personal",
    techUsed: [
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
      <FontAwesomeIcon icon={faDatabase} />,
      <FontAwesomeIcon icon={faNodeJs} />,
    ],
  },
  {
    title: "Djurappen",
    description: "React, API & Framer Motion",
    imageUrl: "/djurappen.JPG",
    link: "https://github.com/gutamuw/animalFeeder",
    category: "Personal",
    techUsed: [
      <FontAwesomeIcon icon={faReact} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faSass} />,
    ],
  },
  {
    title: "Halldoffs.se",
    description: "Website project",
    imageUrl: "/halldoffs-screenshot.png",
    link: "https://www.halldoffs.se/",
    category: "Work",
    techUsed: [
      <FontAwesomeIcon icon={faPhp} />,
      <FontAwesomeIcon icon={faJs} />,
      <FontAwesomeIcon icon={faWordpress} />,
      <FontAwesomeIcon icon={faHtml5} />,
      <FontAwesomeIcon icon={faCss3} />,
    ],
  },
];
